# v3 syntax
version: '3'

# Named volumes
volumes:
  # MySQL Data
  desafio-mysql-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: desafio-mysql
    volumes:
      - desafio-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=desafio
      - MYSQL_DATABASE=desafio
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=desafio

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.1-apache
    container_name: desafio-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
